dataset: MIMIC
diagnoses: data/mimic/diagnoses_icd.csv
admissions: data/mimic/admissions.csv
storage_dir: data/preprocessed
threshold_date: "2180-01-01"
lower_bound: 3
upper_bound: 12
code_length: 3
code_lower_bound: "A"
code_upper_bound: "N"