path_to_training_file: data/preprocessed/mlm/train_transactions.txt
path_to_validation_file: data/preprocessed/mlm/validation_transactions.txt
top_k: 10
metrics: 
 reciprocal_rank: true
 simplified_dcg: true
 precision: false
 recall: false
 f_score: false
 hits: true
 confidence: true