path_to_training_file: data/preprocessed/seq2seq/train_transactions.txt
path_to_validation_file: data/preprocessed/seq2seq/validation_transactions.txt
tokenizer:
 from_huggingface: true
 path_to_saved_tokenizer: windowsartes/bert_tokenizer
confidence_interval:
 use: true
 interval_type: central
 confidence_level: 0.95
metrics: 
 exact_match: false
 accuracy: true
 precision: true
 recall: true
 f_score: false