model:
 type: MultiLabel
 from_pretrained: true
 path_to_pretrained_model: MultiLabel/May-13-2024/18-02/best_model/checkpoint.pt
 backbone:
  from_huggingface: true
  path_to_saved_model: windowsartes/bert
 head:
  n_last_layers: 4
  aggregation: "concatenation"
  mode: "transfer learning"
  hidden_sizes: [1024, 512, 256]
  hidden_use_dropout: True
  hidden_dropout_rate: 0.1
  hidden_use_normalization: True
tokenizer:
 from_huggingface: true
 path_to_saved_tokenizer: windowsartes/bert_tokenizer
hyperparameters:
 batch_size: 512
 seq_len: 24
validation:
 path_to_data: data/preprocessed/seq2seq/validation_transactions.txt
 threshold: 0.25
 confidence_interval: true
 interval_type: central
 confidence_level: 0.95
 save_graphs: true
 metrics: 
  exact_match: false
  accuracy: true
  precision: true
  recall: true
  f_score: true