model:
 type: MultiLabelHead
 backbone:
  from_huggingface: true
  path_to_saved_model: windowsartes/bert
 head:
  params:
   n_last_layers: 4
   aggregation: "concatenation"
   mode: "transfer learning"
   hidden_sizes: [1024, 512, 256]
   hidden_use_dropout: True
   hidden_dropout_rate: 0.1
   hidden_use_normalization: True
tokenizer:
 from_huggingface: true
 path_to_saved_tokenizer: windowsartes/bert_tokenizer
hyperparameters:
 batch_size: 8
 seq_len: 24
training:
 path_to_data: data/preprocessed/train_transactions_pair.txt
validation:
 path_to_data: data/preprocessed/val_transactions_pair.txt