model:
 type: MultiLabel
 from_pretrained: false
 path_to_pretrained_model: null
 backbone:
  from_huggingface: true
  path_to_saved_model: windowsartes/bert
 head:
  n_last_layers: 4
  aggregation: "concatenation"
  mode: "fine tuning"
  hidden_sizes: [1024,]
  hidden_use_dropout: false
  hidden_dropout_rate: 0.1
  hidden_use_normalization: false
tokenizer:
 from_huggingface: true
 path_to_saved_tokenizer: windowsartes/bert_tokenizer
hyperparameters:
 batch_size: 256
 seq_len: 24
training:
 device: cuda:0
 path_to_data: data/preprocessed/seq2seq/train_transactions.txt
 n_epochs: 15
 n_warmup_epochs: 10
 optimizer_parameters:
  learning_rate: 0.001
  backbone_learning_rate: 0.0001
  adam_beta1: 0.9
  adam_beta2: 0.999
  weight_decay: 0.01
validation:
 path_to_data: data/preprocessed/seq2seq/validation_transactions.txt
 period: 1
 threshold: 0.25
 save_graphs: true
 metrics:
  exact_match: false
  accuracy: true
  precision: true
  recall: true
  f_score: false