model:
 type: EncoderDecoder
 from_encoder_decoder: true
 encode:
  from_huggingface: true
  path_to_saved_model: windowsartes/bert
 decoder:
  from_huggingface: true
  path_to_saved_model: windowsartes/bert
tokenizer:
 from_huggingface: true
 path_to_saved_tokenizer: windowsartes/bert_tokenizer
hyperparameters:
 batch_size: 128
 seq_len: 24
training:
 path_to_data: data/preprocessed/seq2seq/train_transactions.txt
 n_epochs: 10
validation:
 path_to_data: data/preprocessed/seq2seq/validation_transactions.txt
 save_graphs: true