model:
 type: FunnelTransformer
 use_pretrained: false
 path_to_saved_weights: null
 config:
  d_model: 384
  n_head: 1
  d_inner: 1536
tokenizer:
 use_pretrained: true
 path_to_saved_tokenizer: null
hyperparameters:
 batch_size: 1024
 seq_len: 24
storage_path: storage
training:
 device: cpu
 path_to_data: data/val_transactions_single.txt
 n_epochs: 1
 n_warmup_epochs: 30
 n_checkpoints: 1
 optimizer_parameters:
  learning_rate: 0.0001
  adam_beta1: 0.9
  adam_beta2: 0.999
  weight_decay: 0.01
validation:
 path_to_data: data/val_transactions_single.txt
 period: 1
 top_k: 10
 save_graphs: true
 metrics: 
  reciprocal_rank: true
  simplified_dcg: true
  precision: true
  recall: true
  f_score: true
  hit: true
save_trained_model: true