model:
 type: BERT
 use_pretrained: true
 path_to_saved_weights: null
tokenizer:
 use_pretrained: true
 path_to_saved_tokenizer: null
hyperparameters:
 batch_size: 1024
 seq_len: 24
validation:
 path_to_data: data/val_transactions_single.txt
 top_k: 10
 metrics: 
  reciprocal_rank: true
  simplified_dcg: true
  precision: true
  recall: true
  f_score: true
  hit: true
wandb:
 use: false